# build settings
markdown: kramdown
remote_theme: chrisrhymes/bulma-clean-theme
description: Some tips, tools and guides that i like to use
timezone: America/Fortaleza
permalink: pages.github.io/:url

defaults:
  - scope:
      path: "_posts/"
    values:
      static: "true"