# build settings
markdown: kramdown
remote_theme: chrisrhymes/bulma-clean-theme
description: Some tips, tools and guides that i like to use
timezone: America/Fortaleza
baseurl: ""
url: "pages.github.io"
permalink: /:title

defaults:
  - scope:
      path: "_posts/"
    values:
      static: "true"